print ("Hi, Welcome to UAP-B Chatbot or Understand A Partner Better Chatbot! I am Ube, the World's Premier Chatbot designed to help you better understand your partner and store all interactions in a centralized location.")
print("I know what you are thinking. I can just use the Notes app for this, right or look at old text messages?")
print("Well, let's look at this as an opportunity to deepen your understanding of your partner. Maybe you missed something? To afraid to ask because you forgot something? Deleted the dating app without memorizing the details? Don't worry, we got you.")
user_name = input (f"Before we go any further, tell me, what is your first name? ")
print (f"Nice to meet you, {user_name}. As I mentioned earlier, you can call me Ube.")
partner_name = input (f"So, without further ado, {user_name}, what is your partner's first name? ")
print (f"Thank you for sharing that! And if no one has said it yet, {partner_name} is lucky to have you as a partner!")
print (f"Now, let's get to the fun part! You are about to hand over your device or allow {partner_name} to interact with me.")
print (f"Go ahead, please hand me over to {partner_name}.")
print(f"Hi {partner_name}! I'm Ube, a chatbot designed to help you further deepen your connection with your partner.")
number_questions = 3
print(f"To start off, I have {number_questions} inital questions.")
ideal_dinner = input (f"Imagine it is the start of a long 4-day weekend and you have no evening plans. {user_name} tells you that they want to treat you to your fav. It will probably be ")
print (f"Ohhh, you would be crazy to not love {ideal_dinner}. Alright, next question.")
ideal_vacay = input (f"During dinner, {user_name} mentions they looked earlier today and flights are cheap to ")
print (f"You have great taste. I will give {user_name} a big hint to book the tickets to {ideal_vacay} if they haven't already.")
ideal_selfcare = input (f"Last one. {user_name} wants to spoil you a bit. Which self-care routine have they agreed to book and attend with you? ")
print(f"One {ideal_selfcare} appointment coming up.")
print (f"Thank you, {partner_name}. It was a plesure speaking with you. Please hand the device back to {user_name}.")